export const moonlightTheme = {
  base: 'vs-dark' as const,
  inherit: true,
  rules: [
    { background: '1b1b25' },
    { token: 'comment', foreground: '7a88cf', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'c099ff', fontStyle: 'italic' },
    { token: 'string', foreground: 'c3e88d' },
    { token: 'number', foreground: 'ff966c' },
    { token: 'type', foreground: 'ffc777' },
    { token: 'class', foreground: 'ffc777' },
    { token: 'function', foreground: '82aaff' },
    { token: 'variable', foreground: 'c8d3f5' },
    { token: 'variable.parameter', foreground: 'c8d3f5' },
    { token: 'constant', foreground: 'ff966c' },
    { token: 'operator', foreground: '86e1fc' },
    { token: 'property', foreground: '4fd6be' },
    { token: 'tag', foreground: 'ff757f' },
    { token: 'attribute.name', foreground: 'c099ff' },
    { token: 'attribute.value', foreground: 'c3e88d' },
  ],
  colors: {
    'editor.background': '#1b1b25',
    'editor.foreground': '#c8d3f5',
    'editor.lineHighlightBackground': '#2f334d80',
    'editorCursor.foreground': '#82aaff',
    'editor.selectionBackground': '#2d3f76',
    'editor.inactiveSelectionBackground': '#2d3f7680',
    'editorIndentGuide.background': '#1e2030',
    'editorIndentGuide.activeBackground': '#3b4261',
    'editorWhitespace.foreground': '#3b4261',
    'editorLineNumber.foreground': '#636da6',
    'editorLineNumber.activeForeground': '#c8d3f5',
    'editorWidget.background': '#1e2030',
    'editorWidget.border': '#3b4261',
  },
};
