version: '3.8'

services:
  app:
    build: .
    container_name: aide-app
    restart: always
    ports:
      - '3000:3000'
    env_file: .env
    volumes:
      - aide_storage:/app/storage

volumes:
  aide_storage:
